import Database from "better-sqlite3";
import fs from "fs";
import path from "path";
import { PlaylistGenerationResult } from "../../shared/types";
import { SmartPlaylistGenerator } from "./smart-playlists";

/**
 * Main playlist management interface.
 *
 * Coordinates smart playlist generation, handles playlist
 * storage, and provides a unified API for playlist operations.
 *
 * Genius playlist generation is now handled by genius-engine.ts
 * and wired through IPC handlers directly.
 */
export class PlaylistManager {
  private smartGenerator: SmartPlaylistGenerator;
  private outputDir: string;

  constructor(db: Database.Database, outputDir?: string) {
    this.outputDir = outputDir || "playlists";
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
    this.smartGenerator = new SmartPlaylistGenerator(db);
  }

  /**
   * Generate a smart playlist based on metadata only.
   * @param playlistType - Type of smart playlist to generate.
   * @param options - Additional parameters for playlist generation.
   */
  generateSmartPlaylist(
    playlistType: string,
    options: Record<string, unknown> = {}
  ): PlaylistGenerationResult {
    return this.smartGenerator.generate(playlistType, options);
  }

  /**
   * Save a generated playlist to file.
   * @param playlistData - Playlist generation result.
   * @param format - Output format: "json" or "m3u".
   * @param filename - Custom filename (without extension).
   * @returns Path to saved file.
   */
  savePlaylist(
    playlistData: PlaylistGenerationResult,
    format: "json" | "m3u" = "json",
    filename?: string
  ): string {
    const safeName = this._sanitizeFilename(
      filename || playlistData.playlistName || "untitled"
    );

    if (format === "json") {
      const filePath = path.join(this.outputDir, `${safeName}.json`);
      fs.writeFileSync(filePath, JSON.stringify(playlistData, null, 2), "utf-8");
      return filePath;
    }

    const filePath = path.join(this.outputDir, `${safeName}.m3u`);
    fs.writeFileSync(filePath, this._createM3uContent(playlistData), "utf-8");
    return filePath;
  }

  /**
   * Generate and save a playlist in one operation.
   * @param category - "smart" or "genius".
   * @param playlistType - Specific type within the category.
   * @param format - Output format.
   * @param options - Additional parameters.
   * @returns Tuple of [playlistData, filePath].
   */
  generateAndSave(
    playlistType: string,
    format: "json" | "m3u" = "json",
    options: Record<string, unknown> = {}
  ): [PlaylistGenerationResult, string] {
    const data = this.generateSmartPlaylist(playlistType, options);
    const filePath = this.savePlaylist(data, format);
    return [data, filePath];
  }

  /**
   * List all available smart playlist types.
   */
  listAvailableTypes(): { smart: string[] } {
    return {
      smart: this.smartGenerator.getAvailableTypes(),
    };
  }

  /**
   * Write an M3U8 file for a playlist by ID (delegates to PlaylistCore for DB access).
   * This is a convenience for saving raw generation results to M3U.
   * @param playlistData - The generation result to export.
   * @param outputPath - Destination file path.
   * @param deviceRoot - If set, paths are made relative to this root.
   */
  savePlaylistToFile(
    playlistData: PlaylistGenerationResult,
    outputPath: string,
    deviceRoot?: string
  ): string {
    const lines: string[] = [
      "#EXTM3U",
      `# Generated by iPodRock: ${playlistData.playlistName}`,
      `# Criteria: ${playlistData.criteria}`,
      `# Generated: ${new Date().toISOString()}`,
      "",
    ];

    for (const track of playlistData.tracks) {
      const dur = Math.floor(track.duration);
      let filepath = track.path;

      if (deviceRoot && filepath) {
        const rel = path.relative(deviceRoot, filepath);
        if (!rel.startsWith("..")) filepath = rel;
      }

      lines.push(`#EXTINF:${dur},${track.artist} - ${track.title}`);
      lines.push(filepath);
    }

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
    return outputPath;
  }

  // -- internal -----------------------------------------------------------

  private _sanitizeFilename(filename: string): string {
    return filename
      .replace(/[<>:"/\\|?*]/g, "_")
      .replace(/\s+/g, " ")
      .replace(/ /g, "_")
      .replace(/^_+|_+$/g, "");
  }

  private _createM3uContent(data: PlaylistGenerationResult): string {
    const lines: string[] = [
      "#EXTM3U",
      `# Generated by iPodRock: ${data.playlistName}`,
      `# Criteria: ${data.criteria}`,
      `# Generated: ${new Date().toISOString()}`,
      "",
    ];

    for (const track of data.tracks) {
      const dur = Math.floor(track.duration);
      lines.push(`#EXTINF:${dur},${track.artist} - ${track.title}`);
      lines.push(track.path);
    }

    return lines.join("\n");
  }
}
