import { Playlist, SmartPlaylistRule } from "../../shared/types";

export interface TagnaviPlaylistInput {
  playlist: Playlist;
  rules: SmartPlaylistRule[];
}

const SUPPORTED_RULE_TYPES: Record<string, string> = {
  artist: "artist",
  album: "album",
  genre: "genre",
};

export function sanitizeQuotedString(input: string): string {
  let s = input
    .replace(/"/g, "'")
    .replace(/[\r\n\t]/g, " ")
    .replace(/[\x00-\x1F\x7F]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return s;
}

export function buildEntryLine(input: TagnaviPlaylistInput): string | null {
  const { playlist, rules } = input;

  const byType: Record<string, string[]> = {};
  for (const rule of rules) {
    const tag = SUPPORTED_RULE_TYPES[rule.ruleType];
    if (!tag) {
      console.warn(`[tagnavi-writer] Unknown rule type '${rule.ruleType}' in playlist '${playlist.name}' — skipped`);
      continue;
    }
    const label = sanitizeQuotedString(rule.targetLabel ?? "");
    if (!label) {
      console.warn(`[tagnavi-writer] Empty label for rule type '${rule.ruleType}' in playlist '${playlist.name}' — skipped`);
      continue;
    }
    if (!byType[tag]) byType[tag] = [];
    byType[tag].push(label);
  }

  const clauses = Object.entries(byType).map(([tag, labels]) => {
    if (labels.length === 1) {
      return `${tag} = "${labels[0]}"`;
    }
    return `${tag} @ ${labels.map((l) => `"${l}"`).join(" ")}`;
  });

  if (clauses.length === 0) return null;

  const rawName = sanitizeQuotedString(playlist.name) || "Untitled";
  return `"${rawName}" -> title ? ${clauses.join(" & ")} = "fmt_ipr_title"`;
}

export function buildTagnaviConfig(
  inputs: TagnaviPlaylistInput[],
  opts?: { now?: () => Date }
): string {
  const now = opts?.now ? opts.now() : new Date();
  const lines: string[] = [
    "#! rockbox/tagbrowser/2.0",
    "# Generated by iPodRocks - do not edit manually",
    `# Generated: ${now.toISOString()}`,
    `%format "fmt_ipr_title" "%s" title`,
    "",
    `%menu_start "ipr_smart" "iPodRocks Smart"`,
  ];

  for (const input of inputs) {
    const entry = buildEntryLine(input);
    if (entry) lines.push(entry);
  }

  return lines.join("\n") + "\n";
}
